ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'

urlpatterns = [
    path('addtocart/<p>',views.addtocart,name='addtocart'),
    path('cartview',views.cartview,name='cartview'),
    path('decrement/<p>',views.decrementcart,name='decrementcart'),
    path('delete/<p>',views.delete_cart,name='delete_cart'),
    path('orderform',views.orderform,name='orderform'),
    path('orderview',views.orderview,name='orderview'),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search',include('search.urls')),
    path('cart',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'

urlpatterns = [
    path('search',views.search,name='search'),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.allcategories,name='allcat'),
    path('view/<p>',views.view,name="view"),
    path('detail/<p>',views.product_detail,name='detail'),
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
from django.http import HttpResponse

# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity * self.product.price

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    order_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.IntegerField()
    acctype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart, Order, Account
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

# Create your views here.
@login_required
def cartview(request):                  # view cart products of current/one user
    total = 0
    u=request.user
    try:
        list1=Cart.objects.filter(user=u)
        for i in list1:
            total+=i.quantity * i.product.price
    except:
        pass
    return render(request,'cartview.html',{'l':list1,'tot':total})

@login_required
def addtocart(request,p):
    item=Product.objects.get(name=p)    # get details of referenced product from product table
    u=request.user                   # get details of current user logged in
    try:
        cart=Cart.objects.get(user=u,product=item)  # for one user only one record with a particular record should be there in Cart table; so we use get()
        if(cart.product.stock > 0):       # check if stock is available before quantity is incremented
            cart.quantity+=1
            cart.save()
            item.stock -= 1
            item.save()
    except:
        if(item.stock>0):                           # check if stock is there to add.
            cart=Cart.objects.create(product=item,user=u,quantity=1)
            # cart.product.stock-=1
            cart.save()
            item.stock-=1
            item.save()
    return cartview(request)

@login_required
def decrementcart(request,p):
    item=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=item)
        if(cart.quantity>1):                # if quantity=1 then, product should be deleted from cart
            cart.quantity-=1
            cart.save()
            item.stock += 1
            item.save()
        else:
            cart.delete()
            item.stock += 1
            item.save()
    except:
        pass
    return cartview(request)

@login_required
def delete_cart(request,p):
    item=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=item)
        cart.delete()
        item.stock+=cart.quantity
        item.save()
    except:
        pass

    return cartview(request)

@login_required
def orderform(request):
    u=request.user
    if request.method=="POST":
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        cart=Cart.objects.filter(user=u)
        total=0
        for i in cart:                      # Total Bill amount of user
            total += i.quantity * i.product.price
        #return HttpResponse(total)
        try:
            a_num=Account.objects.get(acctnum=n)        # to retrieve details of given acctnum for payment
            if a_num:
                if a_num.amount > total:
                    a_num.amount=a_num.amount - total
                    a_num.save()
                    # return HttpResponse("Payment deducted")
                    for i in cart:          # to add all records in this user's cart to order table after payment
                        o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                        o.save()
                    cart.delete()           # to delete cart records of this user after he ordered.
                    msg="Your order has been placed successfully"
                    return render(request,'orderdetail.html',{'msg':msg})
                else:
                    msg="Insufficient balance. Your order cannot be processed"
                    return render(request, 'orderdetail.html', {'msg': msg})
        except:
            pass

    return render(request,'orderform.html')

@login_required()
def orderview(request):
    u=request.user
    msg="Here is the list of your orders"
    o=Order.objects.filter(user=u)
    return render(request,'orderdetail.html',{'msg':msg,'order':o,'u':u})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.http import HttpResponse
from django.db.models import Q

# Create your views here.
def search(request):
    s=""                        #query or word searched
    word=None
    if(request.method=='POST'):
        s=request.POST['s']
        if s:
            word=Product.objects.filter(Q(name__icontains=s) | Q(desc__icontains=s))
            return render(request,'search.html',{'s':s,'word':word})
    return render(request,'category.html')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
<center>
    <img src="{% static 'images/logo.png' %}" height="100px" width="100px" id="logo">
</center>

<nav class="navbar navbar-expand-lg navbar-light" id="navbar1">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Shopy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:view' i.name %}">{{i.name}}</a></li>
<!--            <li><a class="dropdown-item" href="#">Bestsellers</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Your profile</a></li>-->
              {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% if user.is_superuser == False %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup>{{count}}</sup></a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:orderview' %}">Your orders</a>
        </li>
          {% endif %}
          {% else %}

          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}
      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name=s placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

<footer>
    <div id="x">
        <center>
            <p><b><i class="fa-regular fa-copyright"></i>Shopy@pvt ltd. All rights received.</b></p>
        </center>

    </div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row text-white">
        <h4 class="text-center">Shopping Cart</h4>
        <div class="col-sm-7">
            <table class="table-dark table-bordered border-white">
                <tr>
                    <th colspan="5" class="text-center">Cart Items</th>
                </tr>
                    {% for i in l %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
                    <td>{{i.product.name}}</td>
                    <td style="width:150px;">
                        <h6>Product ID : {{i.product.id}}</h6>
                        <h6>Unit price : {{i.product.price}}</h6>
                        <h6>Quantity : {{i.quantity}}</h6>
                        <h6>Total price : {{i.product.price}} X {{i.quantity}}</h6>
                    </td>
                    <td>
                        Subtotal:{{i.subtotal}}             <!-- subtotal is a function of class Cart (models.py).-->
                    </td>
                    <td style="width:60px;">

                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-plus"></i></a>
                        <a href="{% url 'cart:decrementcart' i.product.name %}"><i class="fa-solid fa-minus"></i></a>
                        <a href="{% url 'cart:delete_cart' i.product.name %}"><i class="fa-solid fa-trash"></i></a>

                        {% else %}

                        <a href="{% url 'cart:decrementcart' i.product.name %}"><i class="fa-solid fa-minus"></i></a>
                        <a href="{% url 'cart:delete_cart' i.product.name %}"><i class="fa-solid fa-trash"></i></a>

                        {% endif %}
                    </td>
                </tr>

                {% endfor %}
            </table>
        </div>
        <div class="col-sm-5">
            <table class="table-dark table-bordered border-white">
                <tr>
                    <th colspan="6" class="text-center">Check out</th>
                </tr>
                <tr>
                    <td class="text-white me-2" >Total: {{tot}}</td>
                </tr>
            </table>
            <a href="{% url 'cart:orderform' %}" class="btn btn-primary m-2 fs-6">Place order</a>
            <a href="" class="btn btn-primary m-2 fs-6">Continue Shopping</a>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--{{c}}-->
<img src="{% static 'images/banner.png' %}" height="371px" width="100%">
<div class="container-fluid mt-3 text-white" style="margin-bottom:80px;">
    <h3 class="text-center fw-bold">Our collections</h3>
    <p style="text-align:justify; line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>

<div class="container-fluid" style="margin-bottom:80px;">
    <div class="row">
        {% for i in a %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="{{i.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
<!--    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                    <a href="{% url 'shop:view' i.name %}" class="btn btn-primary">View products</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{{d.image.url}}" class="mt-2" height="500px" width="400px" style="margin-bottom:30px;">
</div>
<div class="text-white" id="p1">
    <h3>{{d.name}}</h3>
    <p>{{d.desc}}</p>
    <p>Price: {{d.price}}</p>
    <p>Stock: {{d.stock}}</p>

    <!-- Depending on if admin or normal user is signed in, detail page display will vary. -->

    {% if user.is_superuser == True %}
    {% if d.stock == 0 %}

    <h4>Out of Stock </h4>
    <a href="{% url 'admin:index' %}" class="btn btn-primary">Add stock</a>
    {% else %}
    <h4>Product in stock</h4>
    <a href="{% url 'admin:index' %}" class="btn btn-primary">Add stock</a>
    {% endif %}

    {% else %}

    {% if d.stock == 0 %}
    <h4>Out of stock</h4>
    {% else %}
    <a href="{% url 'cart:addtocart' d.name %}" class="btn btn-primary">Add to cart</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-white">Login Page</h2>
<center>
    <form method="POST" class="text-white" style="margin-bottom:80px;">
        {% csrf_token %}
        <label>Username:</label>
        <input type="text" name="u"><br><br>
        <label>Password:</label>
        <input type="password" name="p"><br><br>

        <input type="submit" class="btn btn-secondary">
    </form>
</center>
{% endblock %}

ecommerce/templates/orderdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container text-white text-center">
    <div>
      <h5>Your order placed successfully</h5>
        <h6 class="text-danger"> Thank you </h6>
        <a href="{% url 'shop:allcat' %}" class="text-primary">Continue shopping</a>
    </div>
    <div class="mt-4">
        {{msg}}
    </div>
    <div>
        <div class="row border border-success" style="margin-bottom:100px;">
            <div style="text-align:left;">Name of the customer: {{u.username}}</div>
            <br><br>
            {% for i in order %}
            <div class="col-3">
                <img src="{{i.product.image.url}}" height="150px" width="150px" class="me-3 mb-3">
            </div>
            <div class="col-9 w-auto">
                <table class="table-bordered border border-success text-white">
                    <tr style="height:50px;">
                        <td>Product name: {{i.product.name}}</td>
                        <td>Product price: {{i.product.price}}</td>
                        <td>Item count: {{i.no_of_items}}</td>
                        <td>Order date: {{i.order_date}}</td>
                    </tr>
                    <tr style="height:50px;">
                        <td>Delivery address: {{i.address}}</td>
                        <td>Phone: {{i.phone}}</td>
                        <td>Delivery status: {{i.delivery_status}}</td>
                    </tr>
                </table>
            </div>
            {% endfor %}
        </div>

    </div>

</div>
{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h4 class="text-center text-white fw-bold">Order form</h4>
<div class="container text-white" style="position:absolute; left:100px; top:250px; margin-bottom:10px;">
    <form method="POST">
        {% csrf_token %}
        <label>Address: </label>
        <textarea rows="2" cols="20" name="a"></textarea>
        <br><br>
        <label>Phone: </label>
        <input type="number" name="p">
        <br><br>
        <label>Account number: </label>
        <input type="number" name="n">
        <br><br>
        <input type="submit" class="btn btn-info">
    </form>
</div>
{% endblock %}

ecommerce/templates/products.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid text-white" style="margin-top:5px;margin-bottom:80px;">
    <img src="{{b.image.url}}" height="360px" width="100%">
    <br>
    <h3 class="mt-2">{{b.name}}</h3>
    <br>
    <p>{{b.desc}}</p>
</div>

<div class="container-fluid" style="margin-bottom:80px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="{{i.image.url}}" class="card-img-top" style="height:300px;" alt="...">
                <div class="card-body">
                    <h5 class="card-title fw-bold">{{i.name}}</h5>
                    <h6 class="card-title">Rs. {{i.price}}</h6>
                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-white">Registration Page</h2>
<center>
    <form method="POST" enctype="multipart/form-data" class="text-white" style="margin-bottom:80px;">
        {% csrf_token %}
        <label>Username:</label>
        <input type="text" name="u"><br><br>
        <label>Password:</label>
        <input type="password" name="p1"><br><br>
        <label>Confirm password:</label>
        <input type="password" name="p2"><br><br>
        <label>Email id:</label>
        <input type="email" name="e"><br><br>
        <label>First name:</label>
        <input type="text" name="f"><br><br>
        <label>Last name:</label>
        <input type="text" name="l"><br><br>

        <input type="submit" class="btn btn-secondary">
    </form>
</center>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="text-white">
    <h4> Search results </h4>
    {{s}}
    <br>
<!--    {{word}}-->
</div>

<div class="container-fluid" style="margin-bottom:80px;">
    <div class="row">
        {% if word %}
        {% for i in word %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img src="{{i.image.url}}" class="card-img-top" style="height:300px;" alt="...">
                <div class="card-body">
                    <h5 class="card-title fw-bold">{{i.name}}</h5>
                    <h6 class="card-title">Rs. {{i.price}}</h6>
                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h4 class="=text-center text-white">No match found</h4>
        {% endif %}
    </div>
</div>

{% endblock %}